export const fakeGetSurveyUnits = [
  {
    id: '11',
    campaign: 'simpsons2020x00',
    campaignLabel: 'Survey on the Simpsons tv show 2020',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '12',
    campaign: 'simpsons2020x00',
    campaignLabel: 'Survey on the Simpsons tv show 2020',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '13',
    campaign: 'simpsons2020x00',
    campaignLabel: 'Survey on the Simpsons tv show 2020',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '14',
    campaign: 'simpsons2020x00',
    campaignLabel: 'Survey on the Simpsons tv show 2020',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '20',
    campaign: 'vqs2021x00',
    campaignLabel: 'Everyday life and health survey 2021',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '21',
    campaign: 'vqs2021x00',
    campaignLabel: 'Everyday life and health survey 2021',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '22',
    campaign: 'vqs2021x00',
    campaignLabel: 'Everyday life and health survey 2021',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
  {
    id: '23',
    campaign: 'vqs2021x00',
    campaignLabel: 'Everyday life and health survey 2021',
    collectionStartDate: '2020-01-01',
    collectionEndDate: '2022-01-01',
  },
];

const fakeSurveyUnits = [
  {
    id: '11',
    firstName: 'Ted',
    lastName: 'Farmer',
    phoneNumbers: ['+3351231231230'],
    address: {
      L1: 'Ted Farmer',
      L2: null,
      L3: null,
      L4: '1 rue de la gare',
      L5: null,
      L6: '29270 Carhaix',
      L7: 'France',
    },
    geographicalLocation: {
      id: '29024',
      label: 'CARHAIX PLOUGUER',
    },
    priority: true,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '11',
      ec: '11',
      le: '11',
      noi: '11',
      numfa: '11',
      rges: '11',
      ssech: '1',
      nolog: '11',
      nole: '11',
      autre: '11',
      nograp: '11',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '12',
    firstName: 'Cecilia',
    lastName: 'Ortega',
    phoneNumbers: ['+3351231231231'],
    address: {
      L1: 'Cecilia Ortega',
      L2: null,
      L3: null,
      L4: '2 place de la mairie',
      L5: null,
      L6: '90000 Belfort',
      L7: 'France',
    },
    geographicalLocation: {
      id: '90010',
      label: 'BELFORT',
    },
    priority: true,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '12',
      ec: '12',
      le: '12',
      noi: '12',
      numfa: '12',
      rges: '12',
      ssech: '1',
      nolog: '12',
      nole: '12',
      autre: '12',
      nograp: '12',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '13',
    firstName: 'Claude',
    lastName: 'Watkins',
    phoneNumbers: ['+3351231231232'],
    address: {
      L1: 'Claude Watkins',
      L2: null,
      L3: null,
      L4: '3 avenue de la République',
      L5: null,
      L6: '32230 Marciac',
      L7: 'France',
    },
    geographicalLocation: {
      id: '32233',
      label: 'MARCIAC',
    },
    priority: false,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '13',
      ec: '13',
      le: '13',
      noi: '13',
      numfa: '13',
      rges: '13',
      ssech: '2',
      nolog: '13',
      nole: '13',
      autre: '13',
      nograp: '13',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '14',
    firstName: 'Veronica',
    lastName: 'Gill',
    phoneNumbers: ['+3351231231233'],
    address: {
      L1: 'Veronica Gill',
      L2: null,
      L3: null,
      L4: '4 chemin du ruisseau',
      L5: null,
      L6: '44190 Clisson',
      L7: 'France',
    },
    geographicalLocation: {
      id: 44043,
      label: 'CLISSON',
    },
    priority: false,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '14',
      ec: '14',
      le: '14',
      noi: '14',
      numfa: '14',
      rges: '14',
      ssech: '3',
      nolog: '14',
      nole: '14',
      autre: '14',
      nograp: '14',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '20',
    firstName: 'Christine',
    lastName: 'Aguilar',
    phoneNumbers: ['+3351231231234'],
    address: {
      L1: 'Christine Aguilar',
      L2: null,
      L3: null,
      L4: "5 rue de l'école",
      L5: null,
      L6: '59620 Aulnoye-Aimeries',
      L7: 'France',
    },
    geographicalLocation: {
      id: '59033',
      label: 'AULNOYE AYMERIES',
    },
    priority: true,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '20',
      ec: '20',
      le: '20',
      noi: '20',
      numfa: '20',
      rges: '20',
      ssech: '1',
      nolog: '20',
      nole: '20',
      autre: '20',
      nograp: '20',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '21',
    firstName: 'Louise',
    lastName: 'Walker',
    phoneNumbers: ['+3351231231235'],
    address: {
      L1: 'Louise Walker',
      L2: null,
      L3: null,
      L4: '38200 Vienne',
      L5: null,
      L6: '38200 Vienne',
      L7: 'France',
    },
    geographicalLocation: {
      id: '38544',
      label: 'VIENNE',
    },
    priority: true,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '21',
      ec: '21',
      le: '21',
      noi: '21',
      numfa: '21',
      rges: '21',
      ssech: '1',
      nolog: '21',
      nole: '21',
      autre: '21',
      nograp: '21',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '22',
    firstName: 'Anthony',
    lastName: 'Bennett',
    phoneNumbers: ['+3351231231236'],
    address: {
      L1: 'Anthony Bennett',
      L2: null,
      L3: null,
      L4: '7 avenue de la Liberté',
      L5: null,
      L6: '62000 Arras',
      L7: 'France',
    },
    geographicalLocation: {
      id: '62041',
      label: 'ARRAS',
    },
    priority: false,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '22',
      ec: '22',
      le: '22',
      noi: '22',
      numfa: '22',
      rges: '22',
      ssech: '2',
      nolog: '22',
      nole: '22',
      autre: '22',
      nograp: '22',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
  {
    id: '23',
    firstName: 'Christopher',
    lastName: 'Lewis',
    phoneNumbers: ['+3351231231237'],
    address: {
      L1: 'Christopher Lewis',
      L2: null,
      L3: null,
      L4: '8 route du moulin',
      L5: null,
      L6: '35000 Rennes',
      L7: 'France',
    },
    geographicalLocation: {
      id: '35238',
      label: 'RENNES',
    },
    priority: true,
    campaign: '',
    comments: [
      {
        type: 'managementComment',
        value: '',
      },
      {
        type: 'interviewerComment',
        value: '',
      },
    ],
    sampleIdentifiers: {
      bs: '23',
      ec: '23',
      le: '23',
      noi: '23',
      numfa: '23',
      rges: '23',
      ssech: '1',
      nolog: '23',
      nole: '23',
      autre: '23',
      nograp: '23',
    },
    lastState: {},
    states: [],
    contactAttempts: [],
    contactOutcome: {},
  },
];

export const fakeGetSurveyUnitById = searchedId => {
  return fakeSurveyUnits.find(x => x.id === searchedId);
};
